name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create and Activate Virtual Environment
      run: |
        python3 -m venv .venv
        source .venv/bin/activate

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Start Web App
      run: |
        chainlit run pdf_qa.py -w -p 8000 &
        sleep 5
        while ! curl -s http://localhost:8000; do
          sleep 1
        done
