name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: .venv
          environment-file: environment.yml

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build and Deploy
        run: |
          cd docs
          python -m http.server 8000 &
          cd ..
          echo 'Server started'
          
          echo 'Waiting for server to start...'
          sleep 3

          status_code=$(curl --write-out %{http_code} --silent --output /dev/null http://localhost:8000)
          
          if [[ "$status_code" == "200" ]]; then
            echo "Server is running. Deploying..."
            touch .nojekyll
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"
            git add .
            git commit -m "Deploying to GitHub Pages"
            git push origin main
            echo "Deployment successful!"
          else
            echo "Failed to start server. Please check logs for details."
            exit 1
          fi
