name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Miniconda
        run: |
          sudo apt-get update
          sudo apt-get install -yq python3-pip
          sudo apt-get install -yq python3-dev
          curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          bash Miniconda3-latest-Linux-x86_64.sh -b
          source $HOME/miniconda3/etc/profile.d/conda.sh
        shell: bash

      - name: Update Conda
        run: conda update -n base -c defaults conda

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: .venv
          environment-file: environment.yml

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Start Web App
        run: chainlit run pdf_qa.py -w
